// This file was generated by Prisma.
// Ensure env is loaded reliably even when Prisma runs from a different CWD.
import dotenv from "dotenv";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { defineConfig } from "prisma/config";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// backend/.env (this file is at backend/db/prisma.config.ts)
dotenv.config({ path: path.resolve(__dirname, "../.env") });

export default defineConfig({
  schema: path.resolve(__dirname, "prisma/schema.prisma"),
  migrations: {
    path: path.resolve(__dirname, "prisma/migrations"),
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});
